//
// Created by Tom Murphy on 2020-03-26.
//

#ifndef IMAGECPLUPLUSDEMO2_DEFAULTIMAGEVALUES_H
#define IMAGECPLUPLUSDEMO2_DEFAULTIMAGEVALUES_H

#define CANNY_THRESH 100
#define CANNY_RATIO 3
#define CANNY_KERNEL_SIZE 3
#define CANNY_BLUR_WIDTH 3
#define CANNY_AREA_THRESH 200

#define SMOOTH_CONTOURS_EPSILON 1
#define SMOOTH_CONTOURS_BOOL true
#endif //IMAGECPLUPLUSDEMO2_DEFAULTIMAGEVALUES_H
