//
// Created by Tom Murphy on 2020-03-26.
//

#ifndef IMAGECPLUPLUSDEMO2_DEFAULTIMAGEVALUES_H
#define IMAGECPLUPLUSDEMO2_DEFAULTIMAGEVALUES_H

#define CANNY_THRESH 100
#define CANNY_RATIO 3
#define CANNY_KERNEL_SIZE 3
#define CANNY_BLUR_WIDTH 3
#define CANNY_AREA_THRESH 200

#define HASH_ZOOM 0.4

#define SMOOTH_CONTOURS_EPSILON 1
#define SMOOTH_CONTOURS_BOOL true

#define MATCHING_HASH_DIST 8

//FIXME: group all these default and comment each group
#define NUMBER_OF_IMAGE_RESIZES 1 //FIXME: comment all these in this file
#define PERCENTAGE_IMAGE_RESIZE .7


#endif //IMAGECPLUPLUSDEMO2_DEFAULTIMAGEVALUES_H
